---
apiVersion: v1
kind: Secret
metadata:
  name: rhdh-secrets
  namespace: demo-project
  labels:
    app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
  BACKEND_SECRET: N4KQcvTEIi6lAMGB5S0vHvBZdeAh789+J
  K8S_SA_TOKEN: eyJhbGciOiJSUzI1NiIsImtpZCI6IjJ4ZE96N0VTZzJFczhDdFk1andwVWlqUGJCb2JaQkFWMjFzRm9aTExxaWsifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZW1vLXByb2plY3QiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoicmhkaC1rOHMtc2EtdG9rZW4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoicmhkaC1rOHMtc2EiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiIxYjQ3NmMzZC0xZWU5LTQ5MmMtYTg5ZC03NThiNDFlOGUzMTQiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZGVtby1wcm9qZWN0OnJoZGgtazhzLXNhIn0.USLf58CbK64QXlAGfvuL1ua3czUgpHiwigV5GXLe9JJ0l6vuPZcbB9DCZpqy8dguHNA32YQWMziqPmXuuUkvbumVZfztuxu6FFTQIWigVeEmIdJ42cjxFAot_pFOovuENckWtrItMLXUuQVVGKFwqtdIciSinubEPXTISJrfcXPhIYDU7TJQkLlqDD0KK926S6KvwnvnoWLVOGnMx3ACxqSRnbM8e-uiwUDRkYNvpyqeC54dc_QSW42VNCG9AAUrNmuqJa1_K5drNZfeM4h3M3s5FZlQxTZe8vAr5ObNGYAztZ0amv9cwxarkHI2hHjoYwdl6S_GoTWfLbWA4fjjFPyF1wgihuPZ6momHtZa6Y-jCCJ_yhc2-a_QU1YxSMQ3f12xEpdwUPazjuzTJwgO27hn95_lRPMaXbm0-QsK293j0AieNZ9WrqDsGptXV6C4ORTg8TojsKles9IWO3_JPwGK5KhX7L2awGtvIX3kY8nzHz0VwRsByTvIYnYwtnWOqNOYybszZPIzAxLa8IvmN5LiVflNI26zeB9Z6wveNt3aLegGbzM6AImi_6YgXQbJf-gaFZpK-ioV284TD0bNSCjkXOlwLqXu5J5L2S9fIZ3rUTxs-Cdltj8jt5S0sKaioN3SWTiFpWl5LM28fCpQX_g4-77tl9W4Bj6YZOSfV7s
  GITHUB_TOKEN: <placeholder>
